const fakeJobs = [
  {
    jobId: 1,
    company: {
      companyId: 1,
      companyName: "Techify Solutions",
      logoPath: "/logos/techify.png",
      industry: [{ id: 1, name: "IT" }],
      website: "https://techify.com",
      description: "Leading IT solutions provider.",
      email: "hr@techify.com",
      phoneNumber: "0123456789",
    },
    title: "Frontend Developer",
    jobName: "React Frontend Developer",
    description: "Develop and maintain frontend applications.",
    requirements: "3+ years experience with React and JavaScript.",
    benefits: "Health insurance, Flexible hours, Remote option",
    salaryMin: 1000000,
    salaryMax: 2000000,
    jobType: "Full-time",
    location: "Hà Nội",
    postedAt: "2025-10-29",
    deadline: "2025-11-30",
    isActive: true,
    skills: [{ name: "React" }, { name: "JavaScript" }, { name: "CSS" }],
    categories: [{ name: "IT" }, { name: "Frontend" }],
  },
  {
    jobId: 2,
    company: {
      companyId: 1,
      companyName: "GreenFoods Co.",
      logoPath: "/logos/greenfoods.png",
      industry: [{ id: 2, name: "Food & Beverage" }],
      website: "https://greenfoods.com",
      description: "Organic food distributor.",
      email: "contact@greenfoods.com",
      phoneNumber: "0987654321",
    },
    title: "Marketing Specialist",
    jobName: "Digital Marketing Specialist",
    description: "Plan and execute digital marketing campaigns.",
    requirements: "Experience in SEO, SEM, Social Media Marketing.",
    benefits: "Company trips, Health insurance, Bonuses",
    salaryMin: 2000000,
    salaryMax: 1500000,
    jobType: "Full-time",
    location: "Hồ Chí Minh",
    postedAt: "2025-10-20",
    deadline: "2025-11-15",
    isActive: true,
    skills: [{ name: "SEO" }, { name: "Content Marketing" }],
    categories: [{ name: "Marketing" }, { name: "Digital" }],
  },
  {
    jobId: 3,
    company: {
      companyId: 1,
      companyName: "BuildSmart",
      logoPath: "/logos/buildsmart.png",
      industry: [{ id: 3, name: "Construction" }],
      website: "https://buildsmart.com",
      description: "Smart construction solutions.",
      email: "info@buildsmart.com",
      phoneNumber: "0912345678",
    },
    title: "Civil Engineer",
    jobName: "Senior Civil Engineer",
    description: "Design and oversee construction projects.",
    requirements: "Bachelor's in Civil Engineering, 5+ years experience.",
    benefits: "Insurance, Travel allowance, Bonuses",
    salaryMin: 12000000,
    salaryMax: 25000000,
    jobType: "Full-time",
    location: "Đà Nẵng",
    postedAt: "2025-10-15",
    deadline: "2025-11-25",
    isActive: true,
    skills: [{ name: "AutoCAD" }, { name: "Project Management" }],
    categories: [{ name: "Engineering" }, { name: "Construction" }],
  },
  {
    jobId: 4,
    company: {
      companyId: 4,
      companyName: "EduPro",
      logoPath: "/logos/edupro.png",
      industry: [{ id: 4, name: "Education" }],
      website: "https://edupro.com",
      description: "Education & e-learning platform.",
      email: "support@edupro.com",
      phoneNumber: "0934567890",
    },
    title: "Content Writer",
    jobName: "E-learning Content Writer",
    description: "Create content for online courses.",
    requirements: "Excellent writing skills, Knowledge of LMS platforms.",
    benefits: "Remote work, Flexible hours, Health insurance",
    salaryMin: 17000000,
    salaryMax: 21000000,
    jobType: "Part-time",
    location: "Bình Thuận",
    postedAt: "2025-10-22",
    deadline: "2025-11-10",
    isActive: true,
    skills: [{ name: "Writing" }, { name: "Editing" }],
    categories: [{ name: "Education" }, { name: "Content" }],
  },
  {
    jobId: 5,
    company: {
      companyId: 7,
      companyName: "FinTech Hub",
      logoPath: "/logos/fintech.png",
      industry: [{ id: 5, name: "Finance" }],
      website: "https://fintechhub.com",
      description: "Innovative financial solutions.",
      email: "careers@fintechhub.com",
      phoneNumber: "0945678901",
    },
    title: "Backend Developer",
    jobName: "Node.js Backend Developer",
    description: "Develop and maintain backend services.",
    requirements: "Node.js, Express, MongoDB, REST APIs.",
    benefits: "Health insurance, Bonuses, Training budget",
    salaryMin: 11000000,
    salaryMax: 15000000,
    jobType: "Full-time",
    location: "Hà Nội",
    postedAt: "2025-10-18",
    deadline: "2025-11-20",
    isActive: true,
    skills: [
      { name: "Node.js" },
      { name: "MongoDB" },
      { name: "API Development" },
    ],
    categories: [{ name: "IT" }, { name: "Backend" }],
  },
];

export default fakeJobs;
